/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exerciseOne;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // This program performs arithmetic with two integers

        // declare the variables
        int a, b;
        int sum, difference, product;

        // assign values to the variables
        a = 7;
        b = 4;

        // perform the calculations (sum, diff, prod)
        sum = a + b;
        difference = a - b;
        product = a * b;

        // output the results
        System.out.println("The sum of a and b is: " + sum + "\nThe difference of a and b is: " + difference
                + "\nThe product of a and b is: " + product);
    }
}
